[versions]
minecraft = "1.21.11"
fabric-loader = "0.18.3"
fabric-api = "0.140.0+1.21.11"
modmenu = "17.0.0-beta.1"
cloth-config = "21.11.150"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }

modmenu = { module = "com.terraformersmc:modmenu", version.ref = "modmenu" }
cloth-config = { module = "me.shedaniel.cloth:cloth-config-fabric", version.ref = "cloth-config" }